version: '3.8'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --port 4000 --livereload --watch --force_polling

